---
all:
  children:
    win:
      hosts:
        192.168.1.2:
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
    ansible_user: "{{ win_user }}"
    ansible_password: ""